/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;

/**
 *
 * @author Pato
 */
public class Becas {
    int IDBECA;
    int IDESTUDIANTE;
    String TIPOBECA;
    float VALORMONTOBECA;
    int PORCENTAJEVALORARANCELBECA;
    int PORCENTAJECUBREMANUTENCIONBECA;
    String TIPOFINANCIAMIENTOBECA;
    float VALORMONTOAYUDAECONOMICABECA;
    float VALORMONTOCREDITOEDUCATIVOBECA;
    String RAZON1BECA;
    String RAZON2BECA;
    String RAZON3BECA;
    String RAZON4BECA;
    String RAZON5BECA;
    String RAZON6BECA;

    public Becas(int IDBECA, int IDESTUDIANTE, String TIPOBECA, float VALORMONTOBECA, int PORCENTAJEVALORARANCELBECA, int PORCENTAJECUBREMANUTENCIONBECA, String TIPOFINANCIAMIENTOBECA, float VALORMONTOAYUDAECONOMICABECA, float VALORMONTOCREDITOEDUCATIVOBECA, String RAZON1BECA, String RAZON2BECA, String RAZON3BECA, String RAZON4BECA, String RAZON5BECA, String RAZON6BECA) {
        this.IDBECA = IDBECA;
        this.IDESTUDIANTE = IDESTUDIANTE;
        this.TIPOBECA = TIPOBECA;
        this.VALORMONTOBECA = VALORMONTOBECA;
        this.PORCENTAJEVALORARANCELBECA = PORCENTAJEVALORARANCELBECA;
        this.PORCENTAJECUBREMANUTENCIONBECA = PORCENTAJECUBREMANUTENCIONBECA;
        this.TIPOFINANCIAMIENTOBECA = TIPOFINANCIAMIENTOBECA;
        this.VALORMONTOAYUDAECONOMICABECA = VALORMONTOAYUDAECONOMICABECA;
        this.VALORMONTOCREDITOEDUCATIVOBECA = VALORMONTOCREDITOEDUCATIVOBECA;
        this.RAZON1BECA = RAZON1BECA;
        this.RAZON2BECA = RAZON2BECA;
        this.RAZON3BECA = RAZON3BECA;
        this.RAZON4BECA = RAZON4BECA;
        this.RAZON5BECA = RAZON5BECA;
        this.RAZON6BECA = RAZON6BECA;
    }

    public int getIDBECA() {
        return IDBECA;
    }

    public void setIDBECA(int IDBECA) {
        this.IDBECA = IDBECA;
    }

    public int getIDESTUDIANTE() {
        return IDESTUDIANTE;
    }

    public void setIDESTUDIANTE(int IDESTUDIANTE) {
        this.IDESTUDIANTE = IDESTUDIANTE;
    }

    public String getTIPOBECA() {
        return TIPOBECA;
    }

    public void setTIPOBECA(String TIPOBECA) {
        this.TIPOBECA = TIPOBECA;
    }

    public float getVALORMONTOBECA() {
        return VALORMONTOBECA;
    }

    public void setVALORMONTOBECA(float VALORMONTOBECA) {
        this.VALORMONTOBECA = VALORMONTOBECA;
    }

    public int getPORCENTAJEVALORARANCELBECA() {
        return PORCENTAJEVALORARANCELBECA;
    }

    public void setPORCENTAJEVALORARANCELBECA(int PORCENTAJEVALORARANCELBECA) {
        this.PORCENTAJEVALORARANCELBECA = PORCENTAJEVALORARANCELBECA;
    }

    public int getPORCENTAJECUBREMANUTENCIONBECA() {
        return PORCENTAJECUBREMANUTENCIONBECA;
    }

    public void setPORCENTAJECUBREMANUTENCIONBECA(int PORCENTAJECUBREMANUTENCIONBECA) {
        this.PORCENTAJECUBREMANUTENCIONBECA = PORCENTAJECUBREMANUTENCIONBECA;
    }

    public String getTIPOFINANCIAMIENTOBECA() {
        return TIPOFINANCIAMIENTOBECA;
    }

    public void setTIPOFINANCIAMIENTOBECA(String TIPOFINANCIAMIENTOBECA) {
        this.TIPOFINANCIAMIENTOBECA = TIPOFINANCIAMIENTOBECA;
    }

    public float getVALORMONTOAYUDAECONOMICABECA() {
        return VALORMONTOAYUDAECONOMICABECA;
    }

    public void setVALORMONTOAYUDAECONOMICABECA(float VALORMONTOAYUDAECONOMICABECA) {
        this.VALORMONTOAYUDAECONOMICABECA = VALORMONTOAYUDAECONOMICABECA;
    }

    public float getVALORMONTOCREDITOEDUCATIVOBECA() {
        return VALORMONTOCREDITOEDUCATIVOBECA;
    }

    public void setVALORMONTOCREDITOEDUCATIVOBECA(float VALORMONTOCREDITOEDUCATIVOBECA) {
        this.VALORMONTOCREDITOEDUCATIVOBECA = VALORMONTOCREDITOEDUCATIVOBECA;
    }

    public String getRAZON1BECA() {
        return RAZON1BECA;
    }

    public void setRAZON1BECA(String RAZON1BECA) {
        this.RAZON1BECA = RAZON1BECA;
    }

    public String getRAZON2BECA() {
        return RAZON2BECA;
    }

    public void setRAZON2BECA(String RAZON2BECA) {
        this.RAZON2BECA = RAZON2BECA;
    }

    public String getRAZON3BECA() {
        return RAZON3BECA;
    }

    public void setRAZON3BECA(String RAZON3BECA) {
        this.RAZON3BECA = RAZON3BECA;
    }

    public String getRAZON4BECA() {
        return RAZON4BECA;
    }

    public void setRAZON4BECA(String RAZON4BECA) {
        this.RAZON4BECA = RAZON4BECA;
    }

    public String getRAZON5BECA() {
        return RAZON5BECA;
    }

    public void setRAZON5BECA(String RAZON5BECA) {
        this.RAZON5BECA = RAZON5BECA;
    }

    public String getRAZON6BECA() {
        return RAZON6BECA;
    }

    public void setRAZON6BECA(String RAZON6BECA) {
        this.RAZON6BECA = RAZON6BECA;
    }

    @Override
    public String toString() {
        return "Becas{" + "IDBECA=" + IDBECA + ", IDESTUDIANTE=" + IDESTUDIANTE + ", TIPOBECA=" + TIPOBECA + ", VALORMONTOBECA=" + VALORMONTOBECA + ", PORCENTAJEVALORARANCELBECA=" + PORCENTAJEVALORARANCELBECA + ", PORCENTAJECUBREMANUTENCIONBECA=" + PORCENTAJECUBREMANUTENCIONBECA + ", TIPOFINANCIAMIENTOBECA=" + TIPOFINANCIAMIENTOBECA + ", VALORMONTOAYUDAECONOMICABECA=" + VALORMONTOAYUDAECONOMICABECA + ", VALORMONTOCREDITOEDUCATIVOBECA=" + VALORMONTOCREDITOEDUCATIVOBECA + ", RAZON1BECA=" + RAZON1BECA + ", RAZON2BECA=" + RAZON2BECA + ", RAZON3BECA=" + RAZON3BECA + ", RAZON4BECA=" + RAZON4BECA + ", RAZON5BECA=" + RAZON5BECA + ", RAZON6BECA=" + RAZON6BECA + '}';
    }
    
}
